public class APTSConstants {
	public final static String BUNDLE = 'Bundle';
    public final static String STANDALONE = 'Standalone';
    public final static String PRODUCTSERVICE = 'Product/Service';
    public final static String OPTION = 'Option';
    public final static String CommaDelimeter = ';';
    public final static String AMS = 'AMS';
    public final static String SAP = 'SAP';
    public final static String FLEXPAY = 'Flex Pay';
    public final static String IPP4 = 'IPP 4';
    public final static String IPP6 = 'IPP 6';
    public final static String IPP12 = 'IPP 12';
    public final static String NET30 = 'Net 30';
    public final static String FULLPAY = 'Full Pay';
    public final static String COMPLETE = 'Complete';
    public final static String PENDING = 'Pending';
    public final static String CONTINUEFLOW = 'Continue';
    public final static String SPACE = ' ';
    public final static String DOT = '.';
    public final static String CUSTOMSETTINGRECORD = 'System Properties';
    public final static String PERCENT = '%';
    public final static String DOLLER = '$';
    public final static string Training_Consulting='Training & Consulting';
    public final static string Compliance_Services='Compliance Services';
    
    public APTSConstants(){
        system.debug('inside APTSConstants constructor---->');
    }
     
}