public with sharing class ATA_Utility {
// Methods for determing AssignmentType, gathering the role collection per AssignmentType, gathering the 
// collection of users using the RoleAssignmentType and the UserTerritoryRole mapping in the org, 
// and finally to update the AccountTeamMemberTable from the final collection of User, AccountTeamRoleName, and Sharing settings - through the 
// AccountTeamMember Table.

}